name: Jordan Tomasone
description: Building a better self everyday.
url: 'jordantomasone.com'
baseurl: ''
email: me@jordantomasone.com
twitter: https://www.twitter.com/jordantomasone
twitter-username: jordantomasone
instagram: https://www.instagram.com/jordtomasone
youtube: https://www.youtube.com/channel/UCEE67yJY5rlUFNNabjzlW8w
youtube-username: Jordan's Channel
google_analytics: 'UA-84225533-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
