name: Jordan Tomasone
description: Building a better self everyday.
url: 'www.jordansite.com'
baseurl: ''
email: me@jordantomasone.com
twitter: https://www.twitter.com/jordantwitter
twitter-username: jordantwitter
instagram: https://www.instagram.com/
youtube: https://www.youtube.com
youtube-username: jordanschannel
google_analytics: ''

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
