source 'https://rubygems.org'
ruby '2.3.1'
gem 'jekyll'
gem 'jekyll-sitemap'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'github-pages'
gem 'kramdown'
gem 'rack-contrib'
gem 'rack-jekyll'
gem 'rake'
gem 'puma'
gem 'html-proofer'
